# Generated by Django 2.2.15 on 2021-03-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appointment_confirm_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='confirm_date',
            field=models.DateField(),
        ),
    ]
