# Generated by Django 3.1.7 on 2021-03-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210319_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='confirm_date',
            field=models.DateField(null=True),
        ),
    ]
